"""add profile synthesis fields

Revision ID: 391d1c1fef0d
Revises: 6e3b53a6cdab
Create Date: 2026-05-12 20:14:27.700198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '391d1c1fef0d'
down_revision: Union[str, None] = '6e3b53a6cdab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('career_narrative', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('differentiators', sa.JSON(), nullable=True))
    op.add_column('user_profiles', sa.Column('ats_keywords', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'ats_keywords')
    op.drop_column('user_profiles', 'differentiators')
    op.drop_column('user_profiles', 'career_narrative')
    # ### end Alembic commands ###
