"""add application_attempts table

Revision ID: 7c7afa3e752a
Revises: 8e98c570a450
Create Date: 2026-05-13 20:42:53.965153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7afa3e752a'
down_revision: Union[str, None] = '8e98c570a450'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resume_variant', sa.String(length=50), nullable=True),
    sa.Column('cover_letter_text', sa.Text(), nullable=True),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('confirmation_text', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_attempts')
    # ### end Alembic commands ###
