"""add apply_url ats_type application_status to jobs

Revision ID: 8e98c570a450
Revises: c3bd1243dd3d
Create Date: 2026-05-13 19:52:50.645349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e98c570a450'
down_revision: Union[str, None] = 'c3bd1243dd3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('apply_url', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('ats_type', sa.String(length=20), nullable=True))
    op.add_column('jobs', sa.Column('application_status', sa.String(length=30), nullable=False, server_default='discovered'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'application_status')
    op.drop_column('jobs', 'ats_type')
    op.drop_column('jobs', 'apply_url')
    # ### end Alembic commands ###
