"""add user_settings table

Revision ID: c3bd1243dd3d
Revises: 391d1c1fef0d
Create Date: 2026-05-13 19:35:42.176312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3bd1243dd3d'
down_revision: Union[str, None] = '391d1c1fef0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linkedin_cookie_encrypted', sa.Text(), nullable=True),
    sa.Column('linkedin_search_url', sa.Text(), nullable=True),
    sa.Column('yc_filters', sa.JSON(), nullable=True),
    sa.Column('discovery_enabled', sa.Boolean(), nullable=False),
    sa.Column('discovery_interval_hours', sa.Integer(), nullable=False),
    sa.Column('discovery_last_run_at', sa.DateTime(), nullable=True),
    sa.Column('discovery_last_count', sa.Integer(), nullable=True),
    sa.Column('auto_review_threshold', sa.Integer(), nullable=False),
    sa.Column('auto_apply_threshold', sa.Integer(), nullable=False),
    sa.Column('daily_apply_cap', sa.Integer(), nullable=False),
    sa.Column('default_resume_variant', sa.String(length=50), nullable=True),
    sa.Column('cover_letter_tone', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    # ### end Alembic commands ###
